In [1]:
import numpy as np
import sympy as sp

In [2]:
from IPython.display import display, Latex

def display_func(s, f):
    tex = '$ {} = {} $'.format(s, sp.latex(f))
    display(Latex(tex))

**Транспонированная матрица** ($ A^T $) — матрица, полученная из исходной матрицы $ A $ заменой строк на столбцы.

$$
B = A^T, \quad \text{где} \, b_{ij} = a_{ji}
$$

$$
\begin{pmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33}
\end{pmatrix}^T
=
\begin{pmatrix}
    a_{11} & a_{21} & a_{31} \\
    a_{12} & a_{22} & a_{32} \\
    a_{13} & a_{23} & a_{33}
\end{pmatrix}
$$

In [3]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A, end='\n\n')
print(A.transpose()) # A.T

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]


---

In [4]:
x, y = sp.symbols('x, y')
eq1 = x - 3 * y - 11
eq2 = 4 * x + 5 * y + 7

In [5]:
sp.linsolve([eq1, eq2], [x, y])

{(2, -3)}

**СЛАУ**
$$
\begin{cases}
    x - 3 y = 11 \\
    4 x + 5 y = -7
\end{cases}
$$

$$
\begin{pmatrix}
    1 & -3 \\
    4 & 5
\end{pmatrix}
\begin{pmatrix}
    x \\
    y
\end{pmatrix}
=
\begin{pmatrix}
    11 \\
    -7
\end{pmatrix}
$$

$$
X \vec{a} = \vec{b}
$$

$ X^{-1} X = X X^{-1} = E $

$ E \vec{a} = \vec{a} $

**Единичная матрица** ($ E $) — квадратная матрица, элементы главной диагонали которой равны единицам, а остальные равны нулю.

$$
E =
\begin{pmatrix}
    1 & 0 & ... & 0 \\
    0 & 1 & ... & 0 \\
    . & . & ... & . \\
    0 & 0 & ... & 1 \\
\end{pmatrix}
$$

$$
\vec{a} = X^{-1} \vec{b}
$$

**Обратная матрица**
$$
A^{-1} = \frac{1}{\det(A)}A_+^T
$$

$$
A =
\begin{pmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33}
\end{pmatrix}
$$

**Матрица алгебраических дополнений**
$$
A_+ =
\begin{pmatrix}
    A_{11} & A_{12} & A_{13} \\
    A_{21} & A_{22} & A_{23} \\
    A_{31} & A_{32} & A_{33}
\end{pmatrix}
$$
где $ A_{ij} = (-1)^{i+j} M_{ij} $ - алгебраическое дополнение к $ a_{ij} $ \
где $ M_{ij} $ - минор к $ a_{ij} $, то есть определитель матрицы, полученной вычеркиванием $ i $ строчки и $ j $ столбца.

**Определитель матрицы (determinant)** - 
$$ \det(A) = |A| = \sum\limits_{j=1}^{n} a_{ij }A_{ij} = \sum\limits_{j=1}^{n} (-1)^{i+j} a_{ij} M_{ij} = \det(A^T) $$

$$
\det(A) = a_{11}\begin{vmatrix}a_{22} & a_{23} \\a_{32} & a_{33}\end{vmatrix} -
          a_{12}\begin{vmatrix}a_{21} & a_{23} \\a_{31} & a_{33}\end{vmatrix} +
          a_{13}\begin{vmatrix}a_{21} & a_{22} \\a_{31} & a_{32}\end{vmatrix} = \
          a_{11}(a_{22}a_{33} - a_{23}a_{32}) -
          a_{12}(a_{21}a_{33} - a_{23}a_{31}) +
          a_{13}(a_{21}a_{32} - a_{22}a_{31})
$$

Определитель существует только у квадратных матриц

**вырожденная матрица** - квадратная матрица, у которой определитель равен нулю.

Обратная матрица существует только у квадратной *невырожденной* (определитель не равен нулю) матрицы!

Обратную матрицу можно найти и методом Гаусса, приписав справа единичную матрицу \
и преобразованиями получив слева единичную, после чего справа получится искомая.

Если $ A^T A = A A^T = E $, то есть $ A^T = A^{-1} $, то матрица A *ортогональная*.

---

для матрицы размером $ 2 \times 2 $:
$$
A =
\begin{pmatrix}
    a & b \\
    c & d
\end{pmatrix}
$$

$$
A_+ =
\begin{pmatrix}
    d & -c \\
    -b & a
\end{pmatrix}
$$

$$
\det(A) = |A| = a d - b c
$$

$$
A^{-1} = \frac{1}{a d - b c}
\begin{pmatrix}
    d & -b \\
    -c & a
\end{pmatrix}
$$

---
---
---

Для *любой* матрицы существует **псевдообратная матрица**:
$$
X^{\sim1} = (X^T X)^{-1} X^T
$$

**Переопределенное СЛАУ**
$$
\begin{cases}
    5 x + 7 y - 5 z = -47 \\
    -2 y + 2 z = 10 \\
    -4 x - 8 y - 7 z = 63 \\
    x + y + 2 z = -1 \\
    2 x - y + 2 z = -4 \\
    4 x + y + 4 z = -2
\end{cases}
$$

In [6]:
a1, a2, a3 = sp.symbols('a1, a2, a3')
x, y, z = sp.symbols('x, y, z')
f = a1*x + a2*y + a3*z
display_func("f(a1, a2, a3)", f)

<IPython.core.display.Latex object>

In [7]:
f1 = f.subs({a1: 5, a2: 7, a3: -5})
f2 = f.subs({a1: 0, a2: -2, a3: 2})
f3 = f.subs({a1: -4, a2: -8, a3: -7})
f4 = f.subs({a1: 1, a2: 1, a3: 2})
f5 = f.subs({a1: 2, a2: -1, a3: 2})
f6 = f.subs({a1: 4, a2: 1, a3: 4})
display_func("f1", f1)
display_func("f2", f2)
display_func("f3", f3)
display_func("f4", f4)
display_func("f5", f5)
display_func("f6", f6)

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [8]:
MSE = 1/6 * ((-47 - f1)**2 + (10 - f2)**2 + (63 - f3)**2 + (-1 - f4)**2 + (-4 - f5)**2 + (-2 - f6)**2)
MSE = sp.nsimplify(MSE)
display_func("MSE", MSE)

<IPython.core.display.Latex object>

In [9]:
X = sp.Matrix([[ 5,  7, -5],
               [ 0, -2,  2],
               [-4, -8, -7],
               [ 1,  1,  2],
               [ 2, -1,  2],
               [ 4,  1,  4]])
X

Matrix([
[ 5,  7, -5],
[ 0, -2,  2],
[-4, -8, -7],
[ 1,  1,  2],
[ 2, -1,  2],
[ 4,  1,  4]])

In [10]:
b = sp.Matrix([-47, 10, 63, -1, -4, -2])
b

Matrix([
[-47],
[ 10],
[ 63],
[ -1],
[ -4],
[ -2]])

In [11]:
mul = X.T * X
mul.det()

230238

In [12]:
X_pseudo_inverse = (mul)**(-1) * X.T
X_pseudo_inverse

Matrix([
[ 1130/12791,    565/12791,     913/12791,   118/12791,  3017/25582,  3829/25582],
[  763/38373, -5251/115119, -11134/115119,  -10/115119, -6011/76746, -6323/76746],
[-2869/38373,  2092/115119,  -7622/115119, 1999/115119,   262/38373,   748/38373]])

In [13]:
best_point = X_pseudo_inverse * b
best_point = best_point.evalf()
best_point

Matrix([
[0.00609803768274568],
[  -7.00570713783129],
[ -0.559143147525604]])

In [14]:
print(MSE.subs({x: best_point[0], y: best_point[1], z: best_point[2]}))

36.5242879107706


In [15]:
display_func("x", best_point[0].evalf(4))
display_func("y", best_point[1].evalf(4))
display_func("z", best_point[2].evalf(4))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

псевдообратная матрица поможет только для линейных функций

---
---
---

**Скалярное произведение векторов**

$$
\vec a \cdot \vec b = \langle a, b \rangle =
|\vec a| |\vec b| \cos{\varphi} =
\sum\limits_{i=1}^{n} a_i b_i
$$

**Норма** - длина вектора

$$
|\vec a| = \sqrt{ \langle a, a \rangle } = \sqrt{ \sum\limits_{i=1}^{n} a_i^2 }
$$

In [16]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
a.dot(b)

12

---
---
---